version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: mcp_postgres
    environment:
      POSTGRES_DB: mcp_analytics
      POSTGRES_USER: mcp_user
      POSTGRES_PASSWORD: mcp_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcp_user -d mcp_analytics"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MCP Analytics API
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: mcp_api
    environment:
      DATABASE_URL: postgresql://mcp_user:mcp_password@postgres:5432/mcp_analytics
      PYTHONPATH: /app/src
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./src:/app/src:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: mcp_network